# Add mouse support
set -g mouse on

# remap prefix to Control + a
set -g prefix C-a
# bind 'C-a C-a' to type 'C-a'
bind C-a send-prefix
unbind C-b

# Navigate help and copy modes using Vim keybindings instead of default emacs
setw -g mode-keys vi

# set shortcuts for copying
# https://superuser.com/questions/395158/tmux-copy-mode-select-text-block
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
# copy to clipboard
#bind-key -T copy-mode-vi 'y' send -X copy-selection     # Yank selection in copy mode.
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard" \; send -X copy-selection   # Yank selection in copy mode.
